### ISSUE TITLE
Checklist of features to be documented and tested

### ISSUE THREAD

**Issue by dmitriigriazin** [avito-tech/android-ui-testing#11]
Which features to write about? 
Which tests are missing?

**Comment by dmitriigriazin** [comment]
If we have a checklist, I could complete the docs and tests one by one, so we don't have to do it once

**Comment by nesterov-n** [comment]
In my opinion we should start to document base features:
- [ ] `PageObjectElement`
- [ ] `Checks`
- [ ] `Actions`
- [ ] `ListElement`

All specific cases can be understood by basic concepts.
