### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by dsvoronin** [avito-tech/android-ui-testing#3]
Travis? circleCI?
We need best choice for instrumentation tests

**Comment by dsvoronin** [comment]
Lint is failing too (no more)

**Comment by dsvoronin** [comment]
Lint fixed, basic travis with ./gradlew build added.

+ emulators needed (single api for now) + composer?
+ bintray publish

**Comment by dsvoronin** [comment]
will try to setup in-house CI with hooks to github

**Comment by nesterov-n** [comment]
CI is ready. Shall we close this issue?

**Comment by dsvoronin** [comment]
we also need to automate bintray upload of tags(releases)
it could be a separate issue though

**Comment by dsvoronin** [comment]
and local artifactory snapshots publication
