### ISSUE TITLE
Consider improving ListElement methods signatures?

### ISSUE THREAD

**Issue by dmitriigriazin** [avito-tech/android-ui-testing#7]
`val view: PageObjectElement = typedItemByMatcher(withId(R.id.payment_loading_view))` will actually find item by position:

```
Check descendant view with id: com.avito.android.dev:id/payment_loading_view on 0-th item matching: holder with view
```
because it calls the overload `typedItemByMatcher(
            matcher: Matcher<View>,
            position: Int = 0
    )`

Might be confusing.

**Comment by nesterov-n** [comment]
Seems like this function searches for the first occurrence of a child that matches the passed matcher. What can confuse here?
